AWSTemplateFormatVersion: '2010-09-09'
Description: 'chime-news-feed

  Posts RSS feeds to a Chime Channel via a WebHook

  '
Globals:
  Function:
    Timeout: 180
Parameters:
  ChimeWebHookURL:
    Description: Chime Webhook URL for Sending Events.
    Type: String
  FeedsCheckScheduleExpression:
    Default: rate(5 minutes)
    Description: Rate To Check RSS Feeds for Data
    Type: String
Resources:
  CheckFeedsSchedule:
    Properties:
      Description: 'Scheduled rule to check feeds

        '
      ScheduleExpression:
        Ref: FeedsCheckScheduleExpression
      State: ENABLED
      Targets:
      - Arn:
          Fn::Sub: ${GetItemsFunction.Arn}
        Id: CheckFeedsSchedule
    Type: AWS::Events::Rule
  CheckFeedsSchedulePermissiobn:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::Sub: ${GetItemsFunction.Arn}
      Principal: events.amazonaws.com
      SourceArn:
        Fn::Sub: ${CheckFeedsSchedule.Arn}
    Type: AWS::Lambda::Permission
  FeedsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: title
        AttributeType: S
      KeySchema:
      - AttributeName: title
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::DynamoDB::Table
  GetItemsFunction:
    Properties:
      CodeUri: s3://shhorsfi-sam-deploy/1062bdb6b85d10f4bd6217f3fde6bf31
      Environment:
        Variables:
          FEEDS_TABLE:
            Ref: FeedsTable
          ITEMS_TABLE:
            Ref: ItemsTable
      Handler: app.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: FeedsTable
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ItemsTable
      Runtime: python3.7
    Type: AWS::Serverless::Function
  ItemsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    Type: AWS::DynamoDB::Table
  LoadFeedsFunction:
    Properties:
      CodeUri: s3://shhorsfi-sam-deploy/a3a3fe994ae706abd93a5aa3a1fd28d4
      Environment:
        Variables:
          FEEDS_TABLE:
            Ref: FeedsTable
      Handler: app.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: FeedsTable
      Runtime: python3.7
    Type: AWS::Serverless::Function
  LoadNewsFeedsCustomResource:
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - LoadFeedsFunction
        - Arn
    Type: Custom::LoadNewsFeedsCustomResource
  PostItemsFunction:
    Properties:
      CodeUri: s3://shhorsfi-sam-deploy/914af1dcbbd28aa2f7e36873fa6a8da0
      Environment:
        Variables:
          CHIME_WEBHOOK:
            Ref: ChimeWebHookURL
      Events:
        DynamoDB1:
          Properties:
            BatchSize: 1
            StartingPosition: TRIM_HORIZON
            Stream:
              Fn::GetAtt:
              - ItemsTable
              - StreamArn
          Type: DynamoDB
      Handler: app.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ItemsTable
      Runtime: python3.7
    Type: AWS::Serverless::Function
  PostNotificationsCustomResource:
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - PostNotificationsFunction
        - Arn
    Type: Custom::PostNotificationsCustomResource
  PostNotificationsFunction:
    Properties:
      CodeUri: s3://shhorsfi-sam-deploy/49e8f051b26d9746379c014c1588357e
      Environment:
        Variables:
          CHIME_WEBHOOK:
            Ref: ChimeWebHookURL
      Handler: app.lambda_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
