AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  chime-news-feed

  Posts RSS feeds to a Chime Channel via a WebHook

Parameters:
    ChimeWebHookURL:
        Description: Chime Webhook URL for Sending Events.
        Type: String
    FeedsCheckScheduleExpression:
        Description: Rate To Check RSS Feeds for Data
        Type: String
        Default: rate(5 minutes)

Globals:
  Function:
    Timeout: 180

Resources:
  # Get Items From Feeds
  GetItemsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/get_items/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedsTable
        - DynamoDBCrudPolicy:    
            TableName: !Ref ItemsTable
      Environment:
        Variables:
          FEEDS_TABLE: !Ref FeedsTable
          ITEMS_TABLE: !Ref ItemsTable

  PostItemsFunction:
    # Post Items To WebHook
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/post_items/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:    
            TableName: !Ref ItemsTable      
      Environment:
        Variables:
          CHIME_WEBHOOK: !Ref ChimeWebHookURL
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - ItemsTable
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1

  # Load Feeds
  LoadFeedsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/load_feeds/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedsTable
      Environment:
        Variables:
          FEEDS_TABLE: !Ref FeedsTable

  LoadNewsFeedsCustomResource:
    Type: Custom::LoadNewsFeedsCustomResource
    Properties:
      ServiceToken: !GetAtt LoadFeedsFunction.Arn

  # Post Notifications
  PostNotificationsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/post_notifications/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          CHIME_WEBHOOK: !Ref ChimeWebHookURL

  PostNotificationsCustomResource:
    Type: Custom::PostNotificationsCustomResource
    Properties:
      ServiceToken: !GetAtt PostNotificationsFunction.Arn

  FeedsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ItemsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  CheckFeedsSchedule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: >
        Scheduled rule to check feeds
      ScheduleExpression: !Ref FeedsCheckScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !Sub ${GetItemsFunction.Arn}
          Id: CheckFeedsSchedule

  CheckFeedsSchedulePermissiobn:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Sub ${GetItemsFunction.Arn}
      Principal: 'events.amazonaws.com'
      SourceArn: !Sub ${CheckFeedsSchedule.Arn}